# Generated by Django 5.1.3 on 2025-04-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_age_customuser_gender_customuser_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("Sedentary", "Sedentary"),
                    ("Light", "Light Exercise"),
                    ("Moderate", "Moderate Exercise"),
                    ("Active", "Active"),
                    ("VeryActive", "Very Active"),
                ],
                default="Sedentary",
                max_length=20,
            ),
        ),
    ]
