# Generated by Django 5.1.3 on 2025-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0008_multi_trainer_support"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="users_custo_user_ty_f25e6c_idx",
            old_name="users_custom_user_t_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="users_custo_assigne_9a0142_idx",
            old_name="users_custom_assigne_123456_idx",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.FloatField(blank=True, help_text="Height in cm", null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="specific_injury",
            field=models.TextField(
                blank=True, help_text="Any injuries or health conditions", null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(blank=True, help_text="Weight in kg", null=True),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="users_custo_email_c80f75_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["username"], name="users_custo_usernam_a8ad03_idx"
            ),
        ),
    ]
