# Generated by Django 5.1.3 on 2025-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_devicetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
