# Generated by Django 5.1.3 on 2025-07-23 03:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_add_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                null=True,
                upload_to=users.models.user_profile_picture_upload_path,
            ),
        ),
    ]
