# Generated by Django 5.1.3 on 2025-09-11 01:47

from django.db import migrations, models


def dedupe_trainerclientrelation(apps, schema_editor):
    """
    Ensure at most one approved and one pending relation per client
    by demoting older duplicates to 'rejected' before adding constraints.
    """
    TrainerClientRelation = apps.get_model('users', 'TrainerClientRelation')
    # Clean duplicates for approved
    client_ids = (
        TrainerClientRelation.objects
        .values_list('client_id', flat=True)
        .distinct()
    )
    for client_id in client_ids:
        approved_qs = (
            TrainerClientRelation.objects
            .filter(client_id=client_id, status='approved')
            .order_by('-created_at', '-id')
        )
        if approved_qs.count() > 1:
            keep = approved_qs.first()
            approved_qs.exclude(pk=keep.pk).update(status='rejected')
        pending_qs = (
            TrainerClientRelation.objects
            .filter(client_id=client_id, status='pending')
            .order_by('-created_at', '-id')
        )
        if pending_qs.count() > 1:
            keep = pending_qs.first()
            pending_qs.exclude(pk=keep.pk).update(status='rejected')


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.RunPython(dedupe_trainerclientrelation, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="trainerclientrelation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("client",),
                name="unique_approved_trainer_per_client",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainerclientrelation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("client",),
                name="unique_pending_trainer_request_per_client",
            ),
        ),
    ]
