# Generated by Django 5.1.3 on 2025-09-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_trainerclientrelation_unique_approved_trainer_per_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('trainer', 'Trainer'), ('agent', 'Agent'), ('admin', 'Administrator')], default='client', help_text='Determines user permissions and access levels', max_length=10),
        ),
    ]
