# Generated by Django 4.2.7 on 2026-01-21 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('email', models.EmailField(help_text='Email address for lookup', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time (10 minutes from creation)')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this OTP has been used')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was verified', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'indexes': [models.Index(fields=['email', 'otp_code', 'is_verified'], name='users_otpve_email_0c8c89_idx'), models.Index(fields=['expires_at'], name='users_otpve_expires_4f8a2d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='otpverification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', False)), fields=('user', 'otp_code'), name='unique_unverified_otp_per_user'),
        ),
    ]
