# Generated by Django 5.1.3 on 2026-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_otpverification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devicetoken",
            old_name="updated_at",
            new_name="last_used_at",
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="app_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Soft delete for invalid tokens"
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="platform",
            field=models.CharField(
                choices=[("android", "Android"), ("ios", "iOS"), ("web", "Web")],
                default="android",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "is_active"], name="users_devic_user_id_92ecdc_idx"
            ),
        ),
    ]
