# Generated by Django 5.1.3 on 2026-02-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_rename_updated_at_devicetoken_last_used_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                help_text="User's preferred language for notifications and API responses",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_timezone",
            field=models.CharField(
                default="UTC",
                help_text="User's preferred timezone for localized dates and times",
                max_length=50,
            ),
        ),
    ]
