# Generated by Django 5.1.3 on 2026-03-04 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_customuser_preferred_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration time (15 minutes from creation)"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been consumed"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the token was consumed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
            },
        ),
        migrations.AddField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("password_reset", "Password Reset"),
                ],
                default="registration",
                help_text="Purpose of this OTP (registration or password_reset)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["purpose", "is_verified"], name="users_otpve_purpose_631186_idx"
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["token", "is_used"], name="users_passw_token_766a81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["expires_at"], name="users_passw_expires_853bc2_idx"
            ),
        ),
    ]
