# Generated by Django 5.1.3 on 2026-09-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_add_password_reset_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="preferred_timezone",
            field=models.CharField(
                default="Asia/Damascus",
                help_text="User's preferred timezone for localized dates and times",
                max_length=50,
            ),
        ),
    ]
