# Generated by Django 5.1.3 on 2026-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_customuser_preferred_timezone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="devicetoken",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="otpverification",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "OTP Verification",
                "verbose_name_plural": "OTP Verifications",
            },
        ),
        migrations.AlterModelOptions(
            name="passwordresettoken",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="trainerclientrelation",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Trainer-Client Relation",
                "verbose_name_plural": "Trainer-Client Relations",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, db_index=True, default="0000000000", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Soft delete for invalid tokens"
            ),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="trainerclientrelation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
