# Generated by Django 5.1.3 on 2026-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_customuser_options_alter_devicetoken_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ai_training_consent",
            field=models.BooleanField(
                default=False,
                help_text="User consented to their AI chat data being retained for model training.",
            ),
        ),
    ]
