# Generated by Django 5.1.3 on 2026-09-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_passwordresettoken_token_hash"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="users_passw_token_h_c20844_idx",
            old_name="users_passw_token_h_idx",
        ),
    ]
