# Generated by Django 5.1.3 on 2026-09-01 23:38

import training_platform.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_rename_users_passw_token_h_idx_users_passw_token_h_c20844_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="specific_injury",
            field=training_platform.encrypted_fields.EncryptedTextField(
                blank=True, help_text="Any injuries or health conditions", null=True
            ),
        ),
    ]
