# Generated by Django 5.1.3 on 2026-09-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_encrypt_existing_injury_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="otp_code",
            field=models.CharField(
                help_text="Keyed HMAC-SHA256 of the 6-digit code", max_length=64
            ),
        ),
    ]
