# Generated by Django 5.1.3 on 2026-09-02 11:57

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_otpverification_otp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="workout_reminder_hour",
            field=models.PositiveSmallIntegerField(
                default=18,
                help_text="Local hour (0-23) to send the daily workout reminder.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="preferred_timezone",
            field=models.CharField(
                default=users.models._default_timezone,
                help_text="User's preferred timezone. Used to decide when scheduled notifications fire in the user's own day.",
                max_length=50,
            ),
        ),
    ]
