# Generated by Django 5.1.3 on 2026-09-05 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_activity_level_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(13),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.FloatField(
                blank=True,
                help_text="Height in cm",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100.0),
                    django.core.validators.MaxValueValidator(250.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(
                blank=True,
                help_text="Weight in kg",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30.0),
                    django.core.validators.MaxValueValidator(300.0),
                ],
            ),
        ),
    ]
