# Generated by Django 5.1.3 on 2025-04-22 16:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("calories", models.FloatField()),
                ("protein", models.FloatField()),
                ("carbs", models.FloatField()),
                ("fat", models.FloatField()),
                ("serving_size", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("Lose", "Lose Weight"),
                            ("Maintain", "Maintain Weight"),
                            ("Gain", "Gain Muscle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("daily_calories", models.FloatField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(default=1)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_meals",
                        to="diet.dietplan",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diet.fooditem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFoodPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allergies", models.TextField(blank=True)),
                (
                    "disliked_foods",
                    models.ManyToManyField(
                        blank=True, related_name="disliked_by", to="diet.fooditem"
                    ),
                ),
                (
                    "liked_foods",
                    models.ManyToManyField(
                        blank=True, related_name="liked_by", to="diet.fooditem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
