# Generated by Django 5.1.3 on 2025-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
