# Generated by Django 5.1.3 on 2025-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0002_fooditem_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="category",
            field=models.CharField(
                choices=[
                    ("PROTEIN", "Protein"),
                    ("CARB", "Carbohydrate"),
                    ("FAT", "Healthy Fat"),
                ],
                default="PROTEIN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userfoodpreference",
            name="carb_choices",
            field=models.ManyToManyField(
                limit_choices_to={"category": "CARB"},
                related_name="carb_prefs",
                to="diet.fooditem",
            ),
        ),
        migrations.AddField(
            model_name="userfoodpreference",
            name="fat_choices",
            field=models.ManyToManyField(
                limit_choices_to={"category": "FAT"},
                related_name="fat_prefs",
                to="diet.fooditem",
            ),
        ),
        migrations.AddField(
            model_name="userfoodpreference",
            name="protein_choices",
            field=models.ManyToManyField(
                limit_choices_to={"category": "PROTEIN"},
                related_name="protein_prefs",
                to="diet.fooditem",
            ),
        ),
    ]
