# Generated by Django 5.1.3 on 2025-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0003_fooditem_category_userfoodpreference_carb_choices_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "meal_times",
                    models.CharField(
                        choices=[
                            ("ANY", "Any Time"),
                            ("BREAKFAST", "Breakfast"),
                            ("LUNCH", "Lunch"),
                            ("DINNER", "Dinner"),
                        ],
                        default="ANY",
                        max_length=20,
                    ),
                ),
                ("is_protein", models.BooleanField(default=False)),
                ("is_carb", models.BooleanField(default=False)),
                ("is_fat", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROTEIN", "Protein"),
                    ("CARB", "Carbohydrate"),
                    ("FAT", "Healthy Fat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
