# Generated by Django 5.1.3 on 2025-05-08 12:00

from django.db import migrations



def set_initial_categories(apps, schema_editor):
    FoodCategory = apps.get_model('diet', 'FoodCategory')
    FoodItem = apps.get_model('diet', 'FoodItem')
    
    # Create categories
    breakfast_proteins = FoodCategory.objects.create(
        name="Morning Proteins",
        meal_times="BREAKFAST",
        is_protein=True
    )
    
    
    
    breakfast_carbs = FoodCategory.objects.create(
        name="Morning Carbs",
        meal_times="BREAKFAST",
        is_protein=True
    )
    
   
    
    # Auto-categorize existing items (example logic)
    for item in FoodItem.objects.all():
        if item.protein > 10:  # Example threshold
            item.category = 'PROTEIN'
            item.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0004_foodcategory_alter_fooditem_category"),
    ]

    operations = [ migrations.RunPython(set_initial_categories),]
