# Generated by Django 5.1.3 on 2025-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0005_set_initial_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
