# Generated by Django 5.1.3 on 2025-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0009_alter_fooditem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodcategory",
            name="is_malibu",
            field=models.BooleanField(default=False),
        ),
    ]
