# Generated by Django 5.1.3 on 2025-05-08 14:33

from django.db import migrations



def set_initial_categories(apps, schema_editor):
    FoodCategory = apps.get_model('diet', 'FoodCategory')
    FoodItem = apps.get_model('diet', 'FoodItem')
    
    # Create categories
    
    
    
    
    breakfast_carbs = FoodCategory.objects.create(
        name="Morning Carbs",
        meal_times="BREAKFAST",
        is_protein=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0010_foodcategory_is_malibu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodcategory",
            name="is_malibu",
        ),
    ]
