# Generated by Django 5.1.3 on 2025-05-08 15:29

from django.db import migrations, models

def set_initial_categories(apps, schema_editor):
    FoodCategory = apps.get_model('diet', 'FoodCategory')
    FoodItem = apps.get_model('diet', 'FoodItem')
    
    # Create categories
    
    
    
    
    breakfast_carbs = FoodCategory.objects.create(
        name="Morning Carbs",
        meal_times="BREAKFAST",
        is_protein=True
    )

    
    
class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0011_remove_foodcategory_is_malibu"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodcategory",
            name="is_junk",
            field=models.BooleanField(default=False),
        ),migrations.RunPython(set_initial_categories),
    ]
