# Generated by Django 5.1.3 on 2025-05-08 15:31

from django.db import migrations

def set_initial_categories(apps, schema_editor):
    FoodCategory = apps.get_model('diet', 'FoodCategory')
    FoodItem = apps.get_model('diet', 'FoodItem')
    
    # Create categories
    
    
    
    
    breakfast_carbs = FoodCategory.objects.create(
        name="Morning Carbs",
        meal_times="BREAKFAST",
        is_carb=True
    )

    carbs = FoodCategory.objects.create(
        name="Carbs",
        meal_times="ANY",
        is_carb=True
    )

    proteins = FoodCategory.objects.create(
        name="Proteins",
        meal_times="ANY",
        is_protein=True
    )
    fats = FoodCategory.objects.create(
        name="Fats",
        meal_times="ANY",
        is_fat=True
    )

    
    
    
    
class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0012_foodcategory_is_junk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodcategory",
            name="is_junk",
        ),migrations.RunPython(set_initial_categories),
    ]
