# Generated by Django 5.1.3 on 2025-05-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0013_remove_foodcategory_is_junk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfoodpreference",
            name="carb_choices",
            field=models.ManyToManyField(
                limit_choices_to={"category": "Carbs"},
                related_name="carb_prefs",
                to="diet.fooditem",
            ),
        ),
        migrations.AlterField(
            model_name="userfoodpreference",
            name="fat_choices",
            field=models.ManyToManyField(
                limit_choices_to={"category": "Fats"},
                related_name="fat_prefs",
                to="diet.fooditem",
            ),
        ),
        migrations.AlterField(
            model_name="userfoodpreference",
            name="protein_choices",
            field=models.ManyToManyField(
                limit_choices_to={"category": "Proteins"},
                related_name="protein_prefs",
                to="diet.fooditem",
            ),
        ),
    ]
