# Generated by Django 5.1.3 on 2025-05-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0015_alter_userfoodpreference_carb_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="cost_per_serving",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
