# Generated by Django 5.1.3 on 2025-05-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0016_fooditem_cost_per_serving"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="cost_per_serving",
        ),
    ]
