# Generated by Django 5.1.3 on 2025-05-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0017_remove_fooditem_cost_per_serving"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="food",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="quantity",
        ),
        migrations.AddField(
            model_name="meal",
            name="template",
            field=models.CharField(
                choices=[
                    ("PROTEIN_CARB", "Protein + Carb"),
                    ("PROTEIN_FAT", "Protein + Fat"),
                    ("CARB_FAT", "Carb + Fat"),
                    ("COMPLETE", "Full Meal"),
                ],
                default="COMPLETE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MealComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(default=1)),
                (
                    "portion_type",
                    models.CharField(
                        choices=[
                            ("BASE", "Base Serving"),
                            ("ADJUSTED", "User Adjusted"),
                        ],
                        default="BASE",
                        max_length=20,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diet.fooditem"
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diet.meal"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meal",
            name="foods",
            field=models.ManyToManyField(
                through="diet.MealComponent", to="diet.fooditem"
            ),
        ),
    ]
