# Generated by Django 5.1.3 on 2025-05-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0018_remove_meal_food_remove_meal_quantity_meal_template_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="foods",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="meal_type",
        ),
        migrations.RemoveField(
            model_name="mealcomponent",
            name="portion_type",
        ),
        migrations.AddField(
            model_name="mealcomponent",
            name="meal_time",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                    ("Snack", "Snack"),
                ],
                default="Lunch",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="diet_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals",
                to="diet.dietplan",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="template",
            field=models.CharField(
                choices=[
                    ("PROTEIN_CARB", "Protein + Carb"),
                    ("PROTEIN_FAT", "Protein + Fat"),
                    ("CARB_FAT", "Carb + Fat"),
                    ("COMPLETE", "Complete Meal"),
                ],
                default="COMPLETE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealcomponent",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
