# Generated by Django 5.1.3 on 2025-05-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0019_remove_meal_foods_remove_meal_meal_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealcomponent",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="diet.meal",
            ),
        ),
    ]
