# Generated by Django 5.1.3 on 2025-05-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0020_alter_mealcomponent_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealcomponent",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="diet.meal"
            ),
        ),
    ]
