# Generated by Django 5.1.3 on 2025-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0021_alter_mealcomponent_meal"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="duration_weeks",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
