# Generated by Django 5.1.3 on 2025-05-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0022_dietplan_duration_weeks"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="calories_per_gram",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="carbs_per_gram",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="fat_per_gram",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="protein_per_gram",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="serving_size_grams",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
