# Generated by Django 5.1.3 on 2025-06-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0023_fooditem_calories_per_gram_fooditem_carbs_per_gram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="generated_plan",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="generation_strategy",
            field=models.CharField(
                choices=[("GPT", "AI Generated"), ("FALLBACK", "Rule-Based")],
                default="GPT",
                max_length=20,
            ),
        ),
    ]
