# Generated by Django 5.1.3 on 2025-06-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0024_dietplan_generated_plan_dietplan_generation_strategy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DailyAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("context_data", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
