# Generated by Django 5.1.3 on 2025-07-11 03:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0025_meal_description_meal_image_url_meal_is_ai_generated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., '3 Meals + 1 Snack')",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "meals_per_day",
                    models.PositiveIntegerField(
                        help_text="Number of meals per day (1-6)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "snacks_per_day",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of snacks per day (0-3)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "days_variation",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How often the meal plan repeats (1-7 days)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["meals_per_day", "snacks_per_day"],
            },
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["date", "scheduled_time"]},
        ),
        migrations.AddField(
            model_name="dietplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Trainer who created this plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_diet_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this plan is currently active"
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Estimated duration to complete meal in minutes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="is_liked",
            field=models.BooleanField(
                blank=True, help_text="User's like/dislike rating", null=True
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                    ("Snack", "Snack"),
                ],
                default="Lunch",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="notes",
            field=models.TextField(
                blank=True, help_text="User's notes about this meal"
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="scheduled_time",
            field=models.TimeField(
                blank=True, help_text="Scheduled time for this meal", null=True
            ),
        ),
        migrations.AddField(
            model_name="mealcomponent",
            name="actual_quantity_consumed",
            field=models.FloatField(
                blank=True,
                help_text="Actual quantity consumed (may differ from planned quantity)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mealcomponent",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When this component was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="mealcomponent",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="Whether this component was consumed"
            ),
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="generation_strategy",
            field=models.CharField(
                choices=[
                    ("GPT", "AI Generated"),
                    ("TRAINER", "Trainer Created"),
                    ("FALLBACK", "Rule-Based"),
                ],
                default="GPT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealcomponent",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="diet.meal",
            ),
        ),
        migrations.AlterField(
            model_name="mealcomponent",
            name="quantity",
            field=models.FloatField(help_text="Quantity in grams"),
        ),
        migrations.AlterUniqueTogether(
            name="meal",
            unique_together={("diet_plan", "date", "meal_type", "scheduled_time")},
        ),
        migrations.AddField(
            model_name="dietplan",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used for trainer-created plans",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diet.dietplantemplate",
            ),
        ),
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("meals_completed", models.PositiveIntegerField(default=0)),
                ("total_meals", models.PositiveIntegerField(default=0)),
                ("calories_consumed", models.FloatField(default=0)),
                ("protein_consumed", models.FloatField(default=0)),
                ("carbs_consumed", models.FloatField(default=0)),
                ("fat_consumed", models.FloatField(default=0)),
                ("target_calories", models.FloatField(default=0)),
                ("target_protein", models.FloatField(default=0)),
                ("target_carbs", models.FloatField(default=0)),
                ("target_fat", models.FloatField(default=0)),
                ("is_day_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diet.dietplan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "diet_plan", "date")},
            },
        ),
    ]
