# Generated by Django 5.1.3 on 2025-10-14 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0027_dietconfig_userfoodcategorypreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="smart_score_weight",
            field=models.FloatField(
                default=1.0, help_text="Adaptive weight for smart macro planner"
            ),
        ),
    ]
