# Generated by Django 5.1.3 on 2025-10-14 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0029_dietplan_created_at_nullable_and_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietplan",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
