# Generated by Django 5.1.3 on 2025-10-14 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0031_alter_dietplan_updated_at_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietplan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userfoodcategorypreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
