# Generated by Django 5.1.3 on 2026-01-13 00:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0034_add_vegetable_fruit_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dietplan",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(
                fields=["user", "is_active"], name="diet_dietpl_user_id_e6488b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(
                fields=["user", "start_date"], name="diet_dietpl_user_id_1ae89b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(
                fields=["is_active"], name="diet_dietpl_is_acti_3f8ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealcomponent",
            index=models.Index(fields=["meal"], name="diet_mealco_meal_id_2fa47e_idx"),
        ),
        migrations.AddIndex(
            model_name="mealcomponent",
            index=models.Index(fields=["food"], name="diet_mealco_food_id_a26bd0_idx"),
        ),
    ]
