# Generated by Django 5.1.3 on 2026-01-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0035_alter_dietplan_options_alter_dietplan_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="Whether all components are completed"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["is_completed"], name="diet_meal_is_comp_2d03ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["diet_plan", "date"], name="diet_meal_diet_pl_7d910b_idx"
            ),
        ),
    ]
