# Generated by Django 5.1.3 on 2026-02-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0036_meal_is_completed_meal_diet_meal_is_comp_2d03ba_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplantemplate",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietplantemplate",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietplantemplate",
            name="name_ar",
            field=models.CharField(
                help_text="Template name (e.g., '3 Meals + 1 Snack')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietplantemplate",
            name="name_en",
            field=models.CharField(
                help_text="Template name (e.g., '3 Meals + 1 Snack')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="foodcategory",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="foodcategory",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="name_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON translations for dynamic user content (e.g., {'ar': {'description': '...'}})",
            ),
        ),
    ]
