# Generated by Django 5.1.3 on 2026-09-01 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0037_dietplantemplate_description_ar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyadvice",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="dietconfig",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="foodcategory",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="fooditem",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="mealcomponent",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="userfoodcategorypreference",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="userfoodpreference",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="created_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="end_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="userfoodcategorypreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
