# Generated by Django 5.1.3 on 2026-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0038_alter_dailyadvice_options_alter_dietconfig_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="allergen_source",
            field=models.CharField(
                choices=[
                    ("verified", "Verified / curated"),
                    ("inferred", "Inferred from name (unverified hint)"),
                    ("unknown", "No allergen data"),
                ],
                db_index=True,
                default="unknown",
                help_text="Trust level of `allergens`. 'unknown' must NEVER be treated as safe.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="allergens",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Canonical allergen tags from diet.allergens.ALLERGENS. Never free text.",
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="ingredients_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Raw ingredient list, when the source provides one. Scanned for allergens.",
            ),
        ),
    ]
