# Generated by Django 5.1.3 on 2026-09-01 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0040_backfill_food_allergens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyprogress",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="dietplan",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="dietplantemplate",
            options={"ordering": ["meals_per_day", "snacks_per_day", "id"]},
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["date", "scheduled_time", "id"]},
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(
                fields=["user", "-created_at", "-id"], name="dietplan_owner_recent_idx"
            ),
        ),
    ]
