# Generated by Django 5.1.3 on 2026-09-01 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0042_fix_inverted_plan_dates'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dietplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="dietplan_end_after_start",
            ),
        ),
    ]
