# Generated by Django 5.1.3 on 2026-09-01 22:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0043_dietplan_dietplan_end_after_start"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfoodcategorypreference",
            unique_together={("user", "food", "meal", "macro")},
        ),
    ]
