# Generated by Django 5.1.3 on 2026-09-01 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0044_alter_userfoodcategorypreference_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "meal_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Which meals this dish suits, e.g. ['Lunch','Dinner']. Empty = any.",
                    ),
                ),
                ("cuisine", models.CharField(blank=True, default="", max_length=60)),
                ("prep_minutes", models.PositiveIntegerField(default=15)),
                ("instructions", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="diet_recipe_is_acti_f8ac51_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grams",
                    models.FloatField(help_text="Grams per serving before scaling"),
                ),
                (
                    "scalable",
                    models.BooleanField(
                        default=True,
                        help_text="False pins the amount when the recipe is scaled to a macro target.",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=120)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_lines",
                        to="diet.fooditem",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="diet.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-grams", "id"],
                "unique_together": {("recipe", "food")},
            },
        ),
    ]
