# Generated by Django 5.1.3 on 2026-09-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0045_recipe_recipeingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="calories_per_gram",
            field=models.FloatField(default=0.0),
        ),
    ]
