# Generated by Django 5.1.3 on 2026-09-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0046_fooditem_calories_per_gram_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="allergen_report",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
