# Generated by Django 5.1.3 on 2026-09-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0050_finish_catalogue_repair"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="household_unit",
            field=models.CharField(
                blank=True,
                help_text="What one of these is to a person: egg, slice, cup, tbsp, medium, handful.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="max_units",
            field=models.FloatField(
                blank=True,
                help_text="Most units a person would serve at one meal. Null means unknown.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="min_units",
            field=models.FloatField(
                default=0.5,
                help_text="Fewest units worth serving. A minimum inside the search space, not a floor applied afterwards.",
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="role",
            field=models.CharField(
                choices=[
                    ("staple", "Staple — a meal can be built on it"),
                    ("accompaniment", "Accompaniment — served alongside, gram-capped"),
                    (
                        "condiment",
                        "Condiment — added by the spoon, never a primary source",
                    ),
                ],
                db_index=True,
                default="staple",
                help_text="Whether a meal can be built on this food, served alongside it, or only seasoned with it.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="unit_grams",
            field=models.FloatField(
                blank=True,
                help_text="Grams in one household_unit. Null means unknown; the planner then falls back to grams and caps the portion.",
                null=True,
            ),
        ),
    ]
