# Generated by Django 5.1.3 on 2026-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0052_purge_catalogue_test_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="meal_slots",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Meals this food suits, e.g. ['Breakfast', 'Snack']. Empty means any.",
            ),
        ),
    ]
