# Generated by Django 5.1.3 on 2026-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0053_fooditem_meal_slots"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mealcomponent",
            constraint=models.UniqueConstraint(
                fields=("meal", "food"), name="one_row_per_food_per_meal"
            ),
        ),
    ]
