# Generated by Django 5.1.3 on 2026-09-05 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0054_mealcomponent_one_row_per_food"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="cuisine",
            field=models.CharField(
                choices=[
                    ("universal", "Universal"),
                    ("western", "Western"),
                    ("levantine", "Levantine"),
                ],
                db_index=True,
                default="universal",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="userfoodpreference",
            name="local_ratio",
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name="userfoodpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
