# Generated by Django 5.1.3 on 2026-09-05 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0055_preferences_one_to_one_and_cuisine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="target_carbs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="target_fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="target_protein",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="meal",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="meal",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meals",
                to="diet.recipe",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="shape",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_ar",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_ar",
            field=models.CharField(max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_en",
            field=models.CharField(max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="swap_group",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.CreateModel(
            name="UserFoodWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("observations", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_weights",
                        to="diet.fooditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_weights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="diet_userfo_user_id_684fd3_idx")
                ],
                "unique_together": {("user", "food")},
            },
        ),
    ]
