# Generated by Django 5.1.3 on 2026-09-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0056_meal_identity_targets_user_weights"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfoodweight",
            options={"ordering": ["-updated_at", "-id"]},
        ),
    ]
