# Generated by Django 5.1.3 on 2025-07-02 17:18

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Exercise name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the exercise", null=True
                    ),
                ),
                (
                    "target_muscle",
                    models.CharField(
                        choices=[
                            ("Upper Chest", "Upper Chest"),
                            ("Lower Chest", "Lower Chest"),
                            ("Middle Chest", "Middle Chest"),
                            ("Lateral Deltoid", "Lateral Deltoid"),
                            ("Rear Deltoid", "Rear Deltoid"),
                            ("Front Deltoid", "Front Deltoid"),
                            ("Biceps", "Biceps"),
                            ("Triceps", "Triceps"),
                            ("Forearms", "Forearms"),
                            ("Upper Back", "Upper Back"),
                            ("Lats", "Lats"),
                            ("Lower Back", "Lower Back"),
                            ("Traps", "Traps"),
                            ("Abdominals", "Abdominals"),
                            ("Obliques", "Obliques"),
                            ("Glutes", "Glutes"),
                            ("Front Quads", "Front Quads"),
                            ("Hamstrings", "Hamstrings"),
                            ("Calves", "Calves"),
                            ("Adductors", "Adductors"),
                            ("Abductors", "Abductors"),
                            ("Neck", "Neck"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        help_text="Targeted muscle group for this exercise (granular)",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        help_text="Exercise difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this exercise is available to all trainers",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this exercise is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Trainer who created this exercise (null for global exercises)",
                        limit_choices_to={"user_type": "trainer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("photo", "Photo"),
                            ("text", "Text"),
                        ],
                        help_text="Type of media content",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="URL for video/photo or text content"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Media title", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Media description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="routine.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise Media",
                "verbose_name_plural": "Exercise Media",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Routine name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this routine is active"
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(
                        default=3, help_text="Number of days in the routine plan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True, help_text="Optional scheduling", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Start date for the routine",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date for the routine", null=True
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        help_text="Routine difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=60, help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        help_text="Clients assigned to this routine",
                        limit_choices_to={"user_type": "client"},
                        related_name="assigned_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Trainer who created this routine",
                        limit_choices_to={"user_type": "trainer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercises",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Exercises in this routine",
                        to="routine.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine",
                "verbose_name_plural": "Routines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sets",
                    models.PositiveIntegerField(
                        blank=True, default=3, help_text="Number of sets", null=True
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        blank=True,
                        default=10,
                        help_text="Repetitions per set",
                        null=True,
                    ),
                ),
                (
                    "rest_time",
                    models.IntegerField(
                        blank=True,
                        default=60,
                        help_text="Rest time between sets in seconds",
                        null=True,
                    ),
                ),
                (
                    "day",
                    models.PositiveIntegerField(
                        default=1, help_text="Day of the routine"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Order of the exercise in the routine"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, help_text="Weight in kg (if applicable)", null=True
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Duration for time-based exercises",
                        null=True,
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        blank=True,
                        help_text="Distance in meters (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or instructions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_exercises",
                        to="routine.exercise",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_exercises",
                        to="routine.routine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine Exercise",
                "verbose_name_plural": "Routine Exercises",
                "ordering": ["day", "order"],
            },
        ),
        migrations.CreateModel(
            name="RoutineProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.PositiveIntegerField(help_text="Day of the routine")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Skipped", "Skipped"),
                        ],
                        default="Not Started",
                        help_text="Progress status for this day",
                        max_length=20,
                    ),
                ),
                (
                    "completion_time",
                    models.DurationField(
                        blank=True, help_text="Time taken to complete", null=True
                    ),
                ),
                (
                    "exercises_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of exercises completed"
                    ),
                ),
                (
                    "total_exercises",
                    models.PositiveIntegerField(
                        default=0, help_text="Total exercises for this day"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="User notes about the session"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update time"),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="routine.routine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine Progress",
                "verbose_name_plural": "Routine Progress",
                "ordering": ["day"],
            },
        ),
        migrations.CreateModel(
            name="UserExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the progress is recorded",
                    ),
                ),
                (
                    "completed_sets",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sets completed"
                    ),
                ),
                (
                    "target_sets",
                    models.PositiveIntegerField(
                        default=0, help_text="Total sets required for the exercise"
                    ),
                ),
                (
                    "skipped",
                    models.BooleanField(
                        default=False, help_text="Whether the exercise was skipped"
                    ),
                ),
                (
                    "total_weight",
                    models.FloatField(default=0, help_text="Total weight lifted"),
                ),
                (
                    "total_repetitions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total repetitions completed"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Time spent on exercise", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="User notes about the session"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="routine.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Exercise Progress",
                "verbose_name_plural": "User Exercise Progress",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to="routine.routine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout Session",
                "verbose_name_plural": "Workout Sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Set number in the sequence", null=True
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, help_text="Weight used in kg", null=True
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        blank=True,
                        default=10,
                        help_text="Repetitions completed",
                        null=True,
                    ),
                ),
                (
                    "rest_time",
                    models.IntegerField(
                        blank=True,
                        help_text="Rest time before this set in seconds",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Time taken for this set", null=True
                    ),
                ),
                (
                    "rpe",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rate of Perceived Exertion (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this specific set"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, help_text="Date of the set", null=True
                    ),
                ),
                (
                    "user_exercise_progress",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's exercise progress for this set log",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_logs",
                        to="routine.userexerciseprogress",
                    ),
                ),
                (
                    "workout_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Session this set belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_logs",
                        to="routine.workoutsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise Set Log",
                "verbose_name_plural": "Exercise Set Logs",
                "ordering": ["set_number"],
            },
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["difficulty_level"], name="routine_exe_difficu_da0081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["created_by"], name="routine_exe_created_85dd0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["is_global"], name="routine_exe_is_glob_51d588_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["is_active"], name="routine_exe_is_acti_548d8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["created_by"], name="routine_rou_created_303162_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["is_active"], name="routine_rou_is_acti_f8ab9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["difficulty_level"], name="routine_rou_difficu_c0895c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["start_date"], name="routine_rou_start_d_4a8c99_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routineexercise",
            unique_together={("routine", "exercise", "day", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="routineprogress",
            unique_together={("user", "routine", "day")},
        ),
        migrations.AlterUniqueTogether(
            name="userexerciseprogress",
            unique_together={("user", "exercise", "date")},
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["user", "start_time"], name="routine_wor_user_id_1b9552_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["routine"], name="routine_wor_routine_9185d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(fields=["status"], name="routine_wor_status_06ac74_idx"),
        ),
    ]
