# Generated by Django 5.1.3 on 2024-12-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routine",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="routineexercise",
            name="rest_time",
        ),
        migrations.AddField(
            model_name="exercise",
            name="tips",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="exercise_videos/"),
        ),
        migrations.AddField(
            model_name="routineexercise",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="routineexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routine_exercises",
                to="routine.exercise",
            ),
        ),
        migrations.AlterField(
            model_name="routineexercise",
            name="routine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routine_exercises",
                to="routine.routine",
            ),
        ),
    ]
