# Generated by Django 5.1.3 on 2024-12-14 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0002_remove_routine_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routineexercise",
            name="rest_time",
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
