# Generated by Django 5.1.3 on 2025-07-02 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0002_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "goal",
                    models.CharField(
                        help_text="e.g. Hypertrophy, Strength, Endurance",
                        max_length=100,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutineTemplateExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveIntegerField(default=3)),
                ("reps", models.PositiveIntegerField(default=10)),
                (
                    "rest_time",
                    models.PositiveIntegerField(
                        default=90, help_text="Rest time in seconds"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine.exercise",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine.routinetemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="routinetemplate",
            name="exercises",
            field=models.ManyToManyField(
                related_name="templates",
                through="routine.RoutineTemplateExercise",
                to="routine.exercise",
            ),
        ),
    ]
