# Generated by Django 5.1.3 on 2024-12-14 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0003_routine_is_active_routine_scheduled_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="days",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name="UserRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("progress", models.JSONField(blank=True, null=True)),
                (
                    "routine_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_routines",
                        to="routine.routine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
