# Generated by Django 5.1.3 on 2025-07-10 23:19

import routine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0003_routinetemplate_routinetemplateexercise_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routinetemplate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Routine Template",
                "verbose_name_plural": "Routine Templates",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Exercise demonstration image (optional)",
                null=True,
                upload_to=routine.models.exercise_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="routinetemplate",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Whether this template is visible to all users"
            ),
        ),
    ]
