# Generated by Django 5.1.3 on 2025-07-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0004_add_exercise_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="routinetemplate",
            name="days",
            field=models.PositiveIntegerField(
                default=3, help_text="Number of days in the template plan"
            ),
        ),
        migrations.AddField(
            model_name="routinetemplateexercise",
            name="day",
            field=models.PositiveIntegerField(
                default=1, help_text="Day of the template"
            ),
        ),
    ]
