# Generated by Django 5.1.3 on 2024-12-14 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0004_routine_days_userroutine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userroutine",
            name="user",
        ),
        migrations.AddField(
            model_name="userroutine",
            name="users",
            field=models.ManyToManyField(
                related_name="user_routines", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
