# Generated by Django 5.1.3 on 2024-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0005_remove_userroutine_user_userroutine_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineexercise",
            name="day",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
