# Generated by Django 5.1.3 on 2026-01-13 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0005_add_days_to_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisesetlog",
            name="date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.localdate,
                help_text="Date of the set",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userexerciseprogress",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Date the progress is recorded",
            ),
        ),
        migrations.AddIndex(
            model_name="exercisesetlog",
            index=models.Index(
                fields=["workout_session"], name="routine_exe_workout_aacd42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercisesetlog",
            index=models.Index(fields=["date"], name="routine_exe_date_2e823e_idx"),
        ),
        migrations.AddIndex(
            model_name="exercisesetlog",
            index=models.Index(
                fields=["user_exercise_progress"], name="routine_exe_user_ex_123c1f_idx"
            ),
        ),
    ]
