# Generated by Django 5.1.3 on 2024-12-15 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0006_routineexercise_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="tips",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="video",
        ),
        migrations.RemoveField(
            model_name="userroutine",
            name="progress",
        ),
        migrations.AddField(
            model_name="routine",
            name="exercises",
            field=models.ManyToManyField(blank=True, to="routine.exercise"),
        ),
        migrations.CreateModel(
            name="ExerciseMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("photo", "Photo"),
                            ("text", "Text"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="routine.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("completed_sets", models.PositiveIntegerField(default=0)),
                ("target_sets", models.PositiveIntegerField(default=0)),
                ("skipped", models.BooleanField(default=False)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="routine.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
