# Generated by Django 5.1.3 on 2026-02-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0006_alter_exercisesetlog_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="description_ar",
            field=models.TextField(
                blank=True, help_text="Description of the exercise", null=True
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="Description of the exercise", null=True
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="name_ar",
            field=models.CharField(
                help_text="Exercise name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="name_en",
            field=models.CharField(
                help_text="Exercise name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="routine",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON translations for dynamic user content (e.g., {'ar': {'name': '...', 'description': '...'}})",
            ),
        ),
        migrations.AddField(
            model_name="routinetemplate",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routinetemplate",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routinetemplate",
            name="name_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="routinetemplate",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
