# Generated by Django 5.1.3 on 2026-04-11 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0007_exercise_description_ar_exercise_description_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["user", "status", "start_time"], name="ws_user_status_start_idx"
            ),
        ),
    ]
