# Generated by Django 5.1.3 on 2024-12-19 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0008_routineprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseSetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "user_exercise_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_logs",
                        to="routine.userexerciseprogress",
                    ),
                ),
            ],
        ),
    ]
