# Generated by Django 5.1.3 on 2026-08-31 22:32

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_progress_date(apps, schema_editor):
    """
    Existing rows get `date` = the date they were last updated, which is the best
    available approximation of when that training happened. Without this every
    historical row would be stamped with the migration date, collapsing all past
    progress onto a single day.
    """
    RoutineProgress = apps.get_model("routine", "RoutineProgress")
    db = schema_editor.connection.alias
    qs = RoutineProgress.objects.using(db).all().only("id", "updated_at")
    batch = []
    for row in qs.iterator(chunk_size=1000):
        if row.updated_at:
            row.date = row.updated_at.date()
            batch.append(row)
        if len(batch) >= 1000:
            RoutineProgress.objects.using(db).bulk_update(batch, ["date"])
            batch = []
    if batch:
        RoutineProgress.objects.using(db).bulk_update(batch, ["date"])


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op: the column is dropped by the reversed AddField."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0008_add_workout_session_composite_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routineprogress",
            options={
                "ordering": ["-date", "day"],
                "verbose_name": "Routine Progress",
                "verbose_name_plural": "Routine Progress",
            },
        ),
        migrations.AlterUniqueTogether(
            name="routineprogress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="routineprogress",
            name="date",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.localdate,
                help_text="Calendar date this progress entry belongs to",
            ),
        ),
        migrations.RunPython(backfill_progress_date, noop_reverse),
        migrations.AlterUniqueTogether(
            name="routineprogress",
            unique_together={("user", "routine", "day", "date")},
        ),
        migrations.AddIndex(
            model_name="routineprogress",
            index=models.Index(
                fields=["user", "date"], name="routine_rou_user_id_aee0a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routineprogress",
            index=models.Index(
                fields=["user", "status", "date"], name="routine_rou_user_id_02367e_idx"
            ),
        ),
    ]
