# Generated by Django 5.1.3 on 2026-08-31 22:45

from django.db import migrations, models


STATUS_MAP = {
    "Not Started": "not_started",
    "In Progress": "in_progress",
    "Completed": "completed",
    "Skipped": "skipped",
}


def normalize_forward(apps, schema_editor):
    """Convert Title Case status values to the lowercase convention."""
    RP = apps.get_model("routine", "RoutineProgress")
    db = schema_editor.connection.alias
    for old_val, new_val in STATUS_MAP.items():
        RP.objects.using(db).filter(status=old_val).update(status=new_val)


def normalize_backward(apps, schema_editor):
    RP = apps.get_model("routine", "RoutineProgress")
    db = schema_editor.connection.alias
    for old_val, new_val in STATUS_MAP.items():
        RP.objects.using(db).filter(status=new_val).update(status=old_val)


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0009_alter_routineprogress_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routineprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                default="not_started",
                help_text="Progress status for this day",
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_forward, normalize_backward),
    ]
