# Generated by Django 5.1.3 on 2024-12-21 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0009_exercisesetlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="routineprogress",
            name="routine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="routine.routine",
            ),
        ),
        migrations.AddField(
            model_name="routine",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name="routine",
            name="assigned_to",
        ),
        migrations.DeleteModel(
            name="UserRoutine",
        ),
        migrations.AddField(
            model_name="routine",
            name="assigned_to",
            field=models.ManyToManyField(
                related_name="assigned_routines", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
