# Generated by Django 5.1.3 on 2026-08-31 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0010_normalize_progress_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routineprogress",
            name="routine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="progress",
                to="routine.routine",
            ),
        ),
    ]
