# Generated by Django 5.1.3 on 2026-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0011_alter_routineprogress_routine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routinetemplateexercise",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="routine",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="routine",
            name="end_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="End date for the routine",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="routinetemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
