# Generated by Django 5.1.3 on 2026-09-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0012_alter_routinetemplateexercise_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
