# Generated by Django 5.1.3 on 2026-09-01 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0013_delete_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
            },
        ),
        migrations.AlterModelOptions(
            name="exercisemedia",
            options={
                "ordering": ["order", "created_at", "id"],
                "verbose_name": "Exercise Media",
                "verbose_name_plural": "Exercise Media",
            },
        ),
        migrations.AlterModelOptions(
            name="exercisesetlog",
            options={
                "ordering": ["set_number", "id"],
                "verbose_name": "Exercise Set Log",
                "verbose_name_plural": "Exercise Set Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="routine",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Routine",
                "verbose_name_plural": "Routines",
            },
        ),
        migrations.AlterModelOptions(
            name="routineexercise",
            options={
                "ordering": ["day", "order", "id"],
                "verbose_name": "Routine Exercise",
                "verbose_name_plural": "Routine Exercises",
            },
        ),
        migrations.AlterModelOptions(
            name="routineprogress",
            options={
                "ordering": ["-date", "day", "-id"],
                "verbose_name": "Routine Progress",
                "verbose_name_plural": "Routine Progress",
            },
        ),
        migrations.AlterModelOptions(
            name="routinetemplate",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Routine Template",
                "verbose_name_plural": "Routine Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="userexerciseprogress",
            options={
                "ordering": ["-date", "-id"],
                "verbose_name": "User Exercise Progress",
                "verbose_name_plural": "User Exercise Progress",
            },
        ),
        migrations.AlterModelOptions(
            name="workoutsession",
            options={
                "ordering": ["-start_time", "-id"],
                "verbose_name": "Workout Session",
                "verbose_name_plural": "Workout Sessions",
            },
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["created_by", "-created_at", "-id"],
                name="exercise_owner_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["created_by", "-created_at", "-id"],
                name="routine_owner_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routinetemplate",
            index=models.Index(
                fields=["created_by", "-created_at", "-id"],
                name="routinetmpl_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userexerciseprogress",
            index=models.Index(
                fields=["user", "-created_at", "-id"], name="userexprog_recent_idx"
            ),
        ),
    ]
