# Generated by Django 5.1.3 on 2026-09-01 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0014_alter_exercise_options_alter_exercisemedia_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["user", "-start_time", "-id"], name="workoutsess_recent_idx"
            ),
        ),
    ]
