# Generated by Django 5.1.3 on 2026-09-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0015_workoutsession_workoutsess_recent_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routine",
            name="scheduled_date",
        ),
    ]
