# Generated by Django 5.1.3 on 2025-12-07 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the achievement (e.g., 'first_workout')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("workout", "Workout Achievements"),
                            ("diet", "Diet Achievements"),
                            ("social", "Social Achievements"),
                            ("challenge", "Challenge Achievements"),
                            ("streak", "Streak Achievements"),
                            ("milestone", "Milestone Achievements"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("criteria", models.JSONField(default=dict)),
                ("points", models.PositiveIntegerField(default=10)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievements/icons/"
                    ),
                ),
                ("badge_color", models.CharField(default="#FFD700", max_length=7)),
                ("is_rare", models.BooleanField(default=False)),
                ("is_secret", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["category", "points", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="achievement_categor_c3f0a3_idx",
                    ),
                    models.Index(
                        fields=["is_rare", "is_active"],
                        name="achievement_is_rare_954ad2_idx",
                    ),
                    models.Index(fields=["key"], name="achievement_key_578edf_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AchievementProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.FloatField(default=0)),
                ("target_value", models.FloatField(default=0)),
                ("progress_percentage", models.FloatField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="achievements.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement Progress",
                "verbose_name_plural": "Achievement Progress",
                "ordering": ["-progress_percentage"],
                "indexes": [
                    models.Index(
                        fields=["user", "progress_percentage"],
                        name="achievement_user_id_8c1b0b_idx",
                    )
                ],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("progress_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="User can feature up to 3 achievements on their profile",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="achievements.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "earned_at"],
                        name="achievement_user_id_f54b28_idx",
                    ),
                    models.Index(
                        fields=["achievement", "earned_at"],
                        name="achievement_achieve_06fdd4_idx",
                    ),
                    models.Index(
                        fields=["user", "is_featured"],
                        name="achievement_user_id_24dba3_idx",
                    ),
                ],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
