# Generated by Django 5.1.3 on 2026-09-01 08:59

import achievements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_achievement_description_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=achievements.models.achievement_icon_upload_path,
            ),
        ),
    ]
