# Generated by Django 5.1.3 on 2026-09-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0003_alter_achievement_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "ordering": ["category", "points", "name", "id"],
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.AlterModelOptions(
            name="achievementprogress",
            options={
                "ordering": ["-progress_percentage", "-id"],
                "verbose_name": "Achievement Progress",
                "verbose_name_plural": "Achievement Progress",
            },
        ),
        migrations.AlterModelOptions(
            name="userachievement",
            options={
                "ordering": ["-earned_at", "-id"],
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
            },
        ),
    ]
