# Generated by Django 5.1.3 on 2025-07-23 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(db_index=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("users", "User Metrics"),
                            ("subscriptions", "Subscription Metrics"),
                            ("content", "Content Metrics"),
                            ("performance", "Performance Metrics"),
                            ("revenue", "Revenue Metrics"),
                            ("engagement", "Engagement Metrics"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Platform Metric",
                "verbose_name_plural": "Platform Metrics",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "recorded_at"],
                        name="analytics_p_metric__d9620e_idx",
                    ),
                    models.Index(
                        fields=["category", "recorded_at"],
                        name="analytics_p_categor_f4a61b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("profile_update", "Profile Update"),
                            ("routine_created", "Routine Created"),
                            ("routine_completed", "Routine Completed"),
                            ("diet_plan_generated", "Diet Plan Generated"),
                            ("meal_completed", "Meal Completed"),
                            ("exercise_completed", "Exercise Completed"),
                            ("subscription_created", "Subscription Created"),
                            ("payment_completed", "Payment Completed"),
                            ("file_uploaded", "File Uploaded"),
                            ("api_request", "API Request"),
                            ("page_view", "Page View"),
                            ("feature_used", "Feature Used"),
                            ("error_occurred", "Error Occurred"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("weight", "Weight"),
                            ("body_fat", "Body Fat Percentage"),
                            ("muscle_mass", "Muscle Mass"),
                            ("workout_duration", "Workout Duration"),
                            ("calories_burned", "Calories Burned"),
                            ("sets_completed", "Sets Completed"),
                            ("reps_completed", "Reps Completed"),
                            ("distance_run", "Distance Run"),
                            ("diet_adherence", "Diet Adherence"),
                            ("meal_completion", "Meal Completion Rate"),
                            ("goal_achievement", "Goal Achievement"),
                            ("streak_count", "Streak Count"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.useractivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Metric",
                "verbose_name_plural": "Performance Metrics",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("weight_gain", "Weight Gain"),
                            ("muscle_gain", "Muscle Gain"),
                            ("strength", "Strength Improvement"),
                            ("endurance", "Endurance Improvement"),
                            ("diet_adherence", "Diet Adherence"),
                            ("workout_frequency", "Workout Frequency"),
                            ("custom", "Custom Goal"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("target_value", models.FloatField()),
                ("current_value", models.FloatField(default=0)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.FloatField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Goal",
                "verbose_name_plural": "User Goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("api_calls", models.PositiveIntegerField(default=0)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(db_index=True, max_length=100)),
                ("used_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.usersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Usage",
                "verbose_name_plural": "Feature Usage",
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("exception_type", models.CharField(blank=True, max_length=200)),
                ("traceback", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.usersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("user", "User Dashboard"),
                            ("trainer", "Trainer Dashboard"),
                            ("admin", "Admin Dashboard"),
                            ("platform", "Platform Overview"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Dashboard",
                "verbose_name_plural": "Analytics Dashboards",
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["dashboard_type", "user", "computed_at"],
                        name="analytics_a_dashboa_bfeb85_idx",
                    ),
                    models.Index(
                        fields=["user", "computed_at"],
                        name="analytics_a_user_id_49902b_idx",
                    ),
                ],
                "unique_together": {
                    ("dashboard_type", "user", "period_start", "period_end")
                },
            },
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "activity_type", "timestamp"],
                name="analytics_u_user_id_471bcf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type", "timestamp"],
                name="analytics_u_activit_f59ac3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["session_id", "timestamp"],
                name="analytics_u_session_f19d5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["user", "metric_type", "recorded_at"],
                name="analytics_p_user_id_391b27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["metric_type", "recorded_at"],
                name="analytics_p_metric__fd091b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performancemetric",
            unique_together={("user", "metric_type", "recorded_at")},
        ),
        migrations.AddIndex(
            model_name="usergoal",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="analytics_u_user_id_cf637e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usergoal",
            index=models.Index(
                fields=["goal_type", "status"], name="analytics_u_goal_ty_a89596_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "started_at"], name="analytics_u_user_id_c1ab02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_id"], name="analytics_u_session_1131bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["started_at", "ended_at"], name="analytics_u_started_2aa02e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureusage",
            index=models.Index(
                fields=["feature_name", "used_at"],
                name="analytics_f_feature_a6b717_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="featureusage",
            index=models.Index(
                fields=["user", "feature_name", "used_at"],
                name="analytics_f_user_id_bae718_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["level", "occurred_at"], name="analytics_e_level_25be23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["user", "occurred_at"], name="analytics_e_user_id_d9be0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["exception_type", "occurred_at"],
                name="analytics_e_excepti_0b7fbc_idx",
            ),
        ),
    ]
