# Generated by Django 5.1.3 on 2026-09-01 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyticsdashboard",
            options={
                "ordering": ["-computed_at", "-id"],
                "verbose_name": "Analytics Dashboard",
                "verbose_name_plural": "Analytics Dashboards",
            },
        ),
        migrations.AlterModelOptions(
            name="errorlog",
            options={
                "ordering": ["-occurred_at", "-id"],
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="featureusage",
            options={
                "ordering": ["-used_at", "-id"],
                "verbose_name": "Feature Usage",
                "verbose_name_plural": "Feature Usage",
            },
        ),
        migrations.AlterModelOptions(
            name="performancemetric",
            options={
                "ordering": ["-recorded_at", "-id"],
                "verbose_name": "Performance Metric",
                "verbose_name_plural": "Performance Metrics",
            },
        ),
        migrations.AlterModelOptions(
            name="platformmetric",
            options={
                "ordering": ["-recorded_at", "-id"],
                "verbose_name": "Platform Metric",
                "verbose_name_plural": "Platform Metrics",
            },
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "ordering": ["-timestamp", "-id"],
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="usergoal",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "User Goal",
                "verbose_name_plural": "User Goals",
            },
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "ordering": ["-started_at", "-id"],
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
            },
        ),
        migrations.AddIndex(
            model_name="usergoal",
            index=models.Index(
                fields=["user", "-created_at", "-id"], name="usergoal_owner_recent_idx"
            ),
        ),
    ]
