# Generated by Django 5.1.3 on 2026-09-01 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_analyticsdashboard_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyticsdashboard",
            index=models.Index(
                fields=["user", "-computed_at", "-id"], name="analyticsda_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["user", "-occurred_at", "-id"], name="errorlog_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureusage",
            index=models.Index(
                fields=["user", "-used_at", "-id"], name="featureusag_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["user", "-recorded_at", "-id"], name="performance_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "-timestamp", "-id"], name="useractivit_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "-started_at", "-id"], name="usersession_recent_idx"
            ),
        ),
    ]
