# Generated by Django 5.1.3 on 2026-09-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_analyticsdashboard_analyticsda_recent_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="errorlog",
            name="session",
        ),
        migrations.RemoveField(
            model_name="errorlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="featureusage",
            name="session",
        ),
        migrations.RemoveField(
            model_name="featureusage",
            name="user",
        ),
        migrations.DeleteModel(
            name="PlatformMetric",
        ),
        migrations.DeleteModel(
            name="ErrorLog",
        ),
        migrations.DeleteModel(
            name="FeatureUsage",
        ),
    ]
