# Generated by Django 5.1.3 on 2025-06-18 19:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Subscription Feature",
                "verbose_name_plural": "Subscription Features",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("pro", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        db_index=True,
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, "Price must be greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Duration must be at least 1 day"
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_diet_access", models.BooleanField(db_index=True, default=False)),
                (
                    "has_routine_access",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "has_challenges_access",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("has_ai_advice", models.BooleanField(db_index=True, default=False)),
                (
                    "has_priority_support",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "max_meals_per_day",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Max meals cannot be negative"
                            )
                        ],
                    ),
                ),
                (
                    "max_routines",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Max routines cannot be negative"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["price"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "plan_type"],
                        name="subscriptio_is_acti_7ba403_idx",
                    ),
                    models.Index(
                        fields=["price", "is_active"],
                        name="subscriptio_price_429ed8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                            ("trial", "Trial"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "trial_end_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("auto_renew", models.BooleanField(db_index=True, default=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("has_diet_access", models.BooleanField(db_index=True, default=False)),
                (
                    "has_routine_access",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "has_challenges_access",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("has_ai_advice", models.BooleanField(db_index=True, default=False)),
                (
                    "has_priority_support",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscription.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Usage count cannot be negative"
                            )
                        ],
                    ),
                ),
                (
                    "limit",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Limit cannot be negative"
                            )
                        ],
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("period_end", models.DateTimeField(db_index=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscriptionfeature",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Usage",
                "verbose_name_plural": "Subscription Usage",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Amount cannot be negative"
                            )
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_index=True, default="USD", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="subscriptio_status_af708c_idx",
                    ),
                    models.Index(
                        fields=["payment_method", "status"],
                        name="subscriptio_payment_3e6100_idx",
                    ),
                    models.Index(
                        fields=["transaction_id"], name="subscriptio_transac_71bc33_idx"
                    ),
                    models.Index(
                        fields=["payment_intent_id"],
                        name="subscriptio_payment_cc464e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "end_date"], name="subscriptio_status_736288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "status"], name="subscriptio_user_id_f643d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["trial_end_date", "status"],
                name="subscriptio_trial_e_149006_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["auto_renew", "status"], name="subscriptio_auto_re_b2d8fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionusage",
            index=models.Index(
                fields=["subscription", "feature"],
                name="subscriptio_subscri_bb545b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionusage",
            index=models.Index(
                fields=["period_end"], name="subscriptio_period__c67117_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscriptionusage",
            unique_together={("subscription", "feature", "period_start")},
        ),
    ]
