# Generated by Django 5.1.3 on 2025-06-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_transaction_reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("syriatel_cash", "Syriatel Cash"),
                    ("baraka_bank", "Al-Baraka Bank"),
                    ("bemo_bank", "BEMO Bank"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("apple_pay", "Apple Pay"),
                    ("google_pay", "Google Pay"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="stripe",
                max_length=20,
            ),
        ),
    ]
