# Generated by Django 5.1.3 on 2025-06-24 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscription",
            "0002_payment_gateway_error_payment_gateway_response_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Price cannot be negative"
                    )
                ],
            ),
        ),
    ]
