# Generated by Django 5.1.3 on 2026-07-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_alter_subscriptionplan_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_event_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice_number",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("shamcash", "ShamCash"),
                    ("manual", "Manual"),
                    ("syriatel_cash", "Syriatel Cash"),
                    ("baraka_bank", "Al-Baraka Bank"),
                    ("bemo_bank", "BEMO Bank"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("apple_pay", "Apple Pay"),
                    ("google_pay", "Google Pay"),
                ],
                db_index=True,
                default="shamcash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("authorized", "Authorized"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_event_id__isnull", False)),
                fields=("gateway_event_id",),
                name="uniq_payment_gateway_event_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_transaction_reference__isnull", False)),
                fields=("gateway_transaction_reference",),
                name="uniq_payment_gateway_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_id__isnull", False)),
                fields=("transaction_id",),
                name="uniq_payment_transaction_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_number__isnull", False)),
                fields=("invoice_number",),
                name="uniq_payment_invoice_number",
            ),
        ),
    ]
