# Generated by Django 5.1.3 on 2026-09-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscription",
            "0004_payment_gateway_event_id_payment_invoice_number_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionusage",
            options={
                "ordering": ["-id"],
                "verbose_name": "Subscription Usage",
                "verbose_name_plural": "Subscription Usage",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="subscription.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
