# Generated by Django 5.1.3 on 2026-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscription",
            "0006_alter_payment_options_alter_subscription_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="currency",
            field=models.CharField(
                choices=[("SYP", "Syrian Pound"), ("USD", "US Dollar")],
                db_index=True,
                default="SYP",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("SYP", "Syrian Pound"), ("USD", "US Dollar")],
                db_index=True,
                default="SYP",
                max_length=3,
            ),
        ),
    ]
