# Generated by Django 5.1.3 on 2026-09-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0008_quota_periods_and_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="name_ar",
            field=models.CharField(
                db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
