# Generated by Django 5.1.3 on 2026-02-14 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from first message",
                        max_length=200,
                    ),
                ),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tool_calls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tool calls GPT made for this turn",
                    ),
                ),
                (
                    "tool_results",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Data returned by each tool call",
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_assistant.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AITrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_context_snapshot",
                    models.JSONField(
                        help_text="Profile + plan state at interaction time"
                    ),
                ),
                ("user_message", models.TextField()),
                ("tools_called", models.JSONField(default=list)),
                ("tool_results", models.JSONField(default=list)),
                ("ai_response", models.TextField()),
                ("response_tokens", models.IntegerField(default=0)),
                ("response_latency_ms", models.IntegerField(default=0)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[("positive", "👍"), ("negative", "👎")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_training_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_data",
                        to="ai_assistant.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Training Data",
                "verbose_name_plural": "AI Training Data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_tokens", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Cost",
                "verbose_name_plural": "Usage Costs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workout_completed", "Workout Completed"),
                            ("workout_abandoned", "Workout Abandoned"),
                            ("set_logged", "Set Logged"),
                            ("routine_day_completed", "Routine Day Completed"),
                            ("meal_completed", "Meal Completed"),
                            ("plan_generated", "Plan Generated"),
                            ("chat_opened", "Chat Opened"),
                            ("achievement_earned", "Achievement Earned"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Behavior Event",
                "verbose_name_plural": "User Behavior Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("chat_summary", "Chat Summary"),
                            ("training_pattern", "Training Pattern"),
                            ("diet_pattern", "Diet Pattern"),
                            ("behavior_profile", "Behavior Profile"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.JSONField(help_text="Structured insight data")),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="0.0–1.0 confidence score"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null = never expires (e.g. chat summaries)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Insight",
                "verbose_name_plural": "User Insights",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "is_active"], name="ai_assistan_user_id_8d8604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["updated_at", "is_active"],
                name="ai_assistan_updated_dc89d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="ai_assistan_session_915d74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitrainingdata",
            index=models.Index(
                fields=["user", "created_at"], name="ai_assistan_user_id_6b0e97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitrainingdata",
            index=models.Index(
                fields=["user_feedback"], name="ai_assistan_user_fe_3ca16d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagecost",
            index=models.Index(
                fields=["date", "estimated_cost_usd"],
                name="ai_assistan_date_661075_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usagecost",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="userbehaviorevent",
            index=models.Index(
                fields=["user", "created_at"], name="ai_assistan_user_id_549cff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="ai_assistan_event_t_33612a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinsight",
            index=models.Index(
                fields=["user", "insight_type"], name="ai_assistan_user_id_23d1ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinsight",
            index=models.Index(
                fields=["expires_at"], name="ai_assistan_expires_b22d74_idx"
            ),
        ),
    ]
