# Generated by Django 5.1.3 on 2026-09-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_alter_aitrainingdata_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitrainingdata",
            name="consented",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="User opted in to their data being retained for model training.",
            ),
        ),
        migrations.AddField(
            model_name="aitrainingdata",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_data",
                to="ai_assistant.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="aitrainingdata",
            name="retain_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Purge date. Rows past this are deleted by purge_expired_training_data.",
                null=True,
            ),
        ),
    ]
