# Generated by Django 5.1.3 on 2026-09-01 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_assistant",
            "0003_aitrainingdata_consented_aitrainingdata_message_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aitrainingdata",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "AI Training Data",
                "verbose_name_plural": "AI Training Data",
            },
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-updated_at", "-id"],
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="usagecost",
            options={
                "ordering": ["-date", "-id"],
                "verbose_name": "Usage Cost",
                "verbose_name_plural": "Usage Costs",
            },
        ),
        migrations.AlterModelOptions(
            name="userbehaviorevent",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "User Behavior Event",
                "verbose_name_plural": "User Behavior Events",
            },
        ),
        migrations.AlterModelOptions(
            name="userinsight",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "User Insight",
                "verbose_name_plural": "User Insights",
            },
        ),
        migrations.AddIndex(
            model_name="aitrainingdata",
            index=models.Index(
                fields=["user", "-created_at", "-id"], name="aitraindata_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-created_at", "-id"],
                name="chatsession_owner_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userbehaviorevent",
            index=models.Index(
                fields=["user", "-created_at", "-id"], name="ubehavevent_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinsight",
            index=models.Index(
                fields=["user", "-created_at", "-id"],
                name="userinsight_owner_recent_idx",
            ),
        ),
    ]
