# Generated by Django 5.1.3 on 2026-09-01 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0004_alter_aitrainingdata_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-updated_at", "-id"], name="chatsession_recent_idx"
            ),
        ),
    ]
