# Generated by Django 5.1.3 on 2025-09-13 03:50

import django.core.validators
import wallet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprofile",
            name="daily_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="monthly_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(
                default=wallet.models.generate_reference_id, max_length=36, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddIndex(
            model_name="agentapikey",
            index=models.Index(fields=["key_id"], name="wallet_agen_key_id_cf1683_idx"),
        ),
        migrations.AddIndex(
            model_name="agentapikey",
            index=models.Index(
                fields=["is_active"], name="wallet_agen_is_acti_5df305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["key"], name="wallet_idem_key_e078a3_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["reference_id"], name="wallet_tran_referen_8e94e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tx_type", "created_at"], name="wallet_tran_tx_type_aa4480_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletauditlog",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="wallet_wall_event_t_b42f5a_idx",
            ),
        ),
    ]
