# Generated by Django 5.1.3 on 2026-07-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_add_audit_hash_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentapikey",
            name="secret_ciphertext",
            field=models.TextField(blank=True, null=True),
        ),
    ]
