# Generated by Django 5.1.3 on 2026-09-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallet",
            "0005_alter_agentapikey_options_alter_agentprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="walletauditlog",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
