# Generated by Django 5.1.3 on 2026-01-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementProxy",
            fields=[],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("social.achievement",),
        ),
        migrations.CreateModel(
            name="ChallengeParticipationProxy",
            fields=[],
            options={
                "verbose_name": "Challenge Participation",
                "verbose_name_plural": "Challenge Participations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("social.challengeparticipation",),
        ),
        migrations.CreateModel(
            name="ChallengeProxy",
            fields=[],
            options={
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("social.challenge",),
        ),
        migrations.CreateModel(
            name="LeaderboardProxy",
            fields=[],
            options={
                "verbose_name": "Leaderboard",
                "verbose_name_plural": "Leaderboards",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("social.leaderboard",),
        ),
        migrations.CreateModel(
            name="NotificationProxy",
            fields=[],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("social.notification",),
        ),
        migrations.CreateModel(
            name="UserAchievementProxy",
            fields=[],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("social.userachievement",),
        ),
    ]
