# Generated by Django 5.1.3 on 2026-09-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationProxy",
        ),
    ]
