# Generated by Django 5.1.3 on 2026-02-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="name_ar",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
