# Generated by Django 5.1.3 on 2026-09-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_achievement_description_ar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentlike",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Comment Like",
                "verbose_name_plural": "Comment Likes",
            },
        ),
        migrations.AlterModelOptions(
            name="postlike",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Post Like",
                "verbose_name_plural": "Post Likes",
            },
        ),
        migrations.AlterModelOptions(
            name="userfollow",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "User Follow",
                "verbose_name_plural": "User Follows",
            },
        ),
    ]
