# Generated by Django 5.1.3 on 2026-09-01 08:59

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_alter_commentlike_options_alter_postlike_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social.models.achievement_icon_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social.models.challenge_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.post_image_upload_path
            ),
        ),
    ]
