# Generated by Django 5.1.3 on 2026-09-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_alter_achievement_icon_alter_challenge_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
