# Generated by Django 5.1.3 on 2026-09-01 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("social", "0005_delete_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
            },
        ),
        migrations.AlterModelOptions(
            name="challengeparticipation",
            options={
                "ordering": ["-joined_at", "-id"],
                "verbose_name": "Challenge Participation",
                "verbose_name_plural": "Challenge Participations",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="leaderboard",
            options={
                "ordering": ["-period_start", "-id"],
                "verbose_name": "Leaderboard",
                "verbose_name_plural": "Leaderboards",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="userachievement",
            options={
                "ordering": ["-earned_at", "-id"],
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
            },
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["creator", "-created_at", "-id"],
                name="challenge_owner_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "-created_at", "-id"], name="comment_owner_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at", "-id"], name="post_owner_recent_idx"
            ),
        ),
    ]
