# Generated by Django 5.1.3 on 2026-09-01 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_alter_challenge_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="challengeparticipation",
            index=models.Index(
                fields=["user", "-joined_at", "-id"], name="challengepa_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["user", "-earned_at", "-id"], name="socialachv_recent_idx"
            ),
        ),
    ]
