# Generated by Django 5.1.3 on 2026-02-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_usernotificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event_id",
            field=models.UUIDField(
                blank=True, help_text="Correlation ID from Domain Event", null=True
            ),
        ),
    ]
