# Generated by Django 5.1.3 on 2026-02-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("event_payload", models.JSONField(help_text="Original event data")),
                ("error_message", models.TextField()),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("is_resolved", models.BooleanField(default=False)),
            ],
        ),
    ]
