# Generated by Django 5.1.3 on 2026-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notification_notificatio_recipie_a972ce_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationfailure",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="usernotificationpreference",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notificationfailure",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
